
Prefix: ""
AnnouncerPrefix: ""
ThankingRewardAmount: 5
ActivatorRewardAmount: 10
BootsActivationTime: 3
CoinsLostPerDeath: 1
CoinsGainedPerKill: 1
TPDelay: 3

SuperBoots Lores:
  Anti Fall:
    - "&7What is fall damage?"
  Strength:
    - "&7Gives you strength &e%level% permanently"
  Regen:
    - "&7Gives you regen &e%level%&7 permanently"
  Glowing:
    - "&7You can pretty much x-ray with these bad boys on"
    - "&7Gives the glowing effect to everyone within &e%glowBlockRange% blocks"
  Speed:
    - "&7Gotta go fast &eâ„¢"
  Jump Boost:
    - "&7This' pretty self explanatory, &oright?"
    - "&7You gain jump boost &e%level%&7 permanently"
  Double Jump:
    - "&7Another obvious one."
    - "&7You can jump another time while midair with these boots on"
  Absorption:
    - "&7You gain &e%absorptionAmount%&7 extra hearts"
  Blindness:
    - "&7I feel bad for the people that are near you..."
    - "&7You blind anyone who is within &e%blindnessBlockRange% blocks&7 of you."
  Coin:
    - "&7These boots are the definition of &dOP"
    - "&7You can gain anywhere from &e1&7 to &e25&7 coins when you kill someone"
  AntiKB:
    - "&7What is knock-back, am I right?"
  Stonks:
    - "&7You can't ever go broke if you never lose coins"
    - "&7You never lose coins when you die with these boots on"
  Levitation:
    - "&7I took levitation classes once, &ebut then I dropped out..."
  Invisibility:
    - "&7Lets switch it up and go &e&oinvisible&7 for a bit!"

Weapons Settings:
  SnowBall Knockback Multiplier: 1.5
  TNT Explosion Time: 2
  FireCharge Velocity Multiplier: 2
  Egg Velocity Multiplier: 2
  Egg Damage: 10

SuperBoots Properties:
  Anti Fall:
    Cooldown: 0
    Duration: 0
  Strength:
    Cooldown: 0
    Duration: 0
    Level: 1
  Regen:
    Cooldown: 0
    Duration: 0
    Level: 1
  Glowing:
    Cooldown: 30
    Duration: 10
    GlowBlockRange: 50
  Speed:
    Cooldown: 60
    Duration: 30
    Level: 1
  Jump Boost:
    Cooldown: 60
    Duration: 30
    Level: 1
  Double Jump:
    Cooldown: 10
    Duration: 0
  Absorption:
    Cooldown: 0
    Duration: 0
    ExtraHeartAmount: 10
  Blindness:
    Cooldown: 60
    Duration: 30
    BlindnessBlockRange: 5
  Coin:
    Cooldown: 0
    Duration: 0
  AntiKB:
    Cooldown: 30
    Duration: 10
  Stonks:
    Cooldown: 0
    Duration: 0
  Levitation:
    Cooldown: 120
    Duration: 5
  Invisibility:
    Cooldown: 60
    Duration: 25

Costs:

  EnderChest: 500

  TP:
    SpecialTP: 500

  OreTP:
    Iron: 20
    IronBlock: 75
    Gold: 200
    GoldBlock: 300
    Diamond: 400
    DiamondBlock: 500
    Emerald: 700

  Ores:
    1:
      CoalBlock: 3
      Iron: 5
      IronBlock: 10
      Gold: 15
      GoldBlock: 20
      Diamond: 25
      DiamondBlock: 50
      Emerald: 75
      EmeraldBlock: 100
    32:
      CoalBlock: 96
      Iron: 160
      IronBlock: 32
      Gold: 480
      GoldBlock: 640
      Diamond: 800
      DiamondBlock: 1600
      Emerald: 2400
      EmeraldBlock: 3200
    64:
      CoalBlock: 192
      Iron: 320
      IronBlock: 640
      Gold: 960
      GoldBlock: 1280
      Diamond: 1600
      DiamondBlock: 3200
      Emerald: 4800
      EmeraldBlock: 6400

  Weapons:
    Knockback: 15
    PositionSwap: 100
    TNT: 20
    Fireball: 50
    InstaKill: 100

  Chat:
    Gray: 0
    LimeGreen: 500
    Yellow: 500
    Blue: 0
    Gold: 0
    Purple: 0

  SuperBoots:
    Anti Fall: 1000
    Strength: 0
    Regen: 2500
    Glowing: 1000
    Speed: 25000
    Jump Boost: 0
    Double Jump: 20000
    Absorption: 5000
    Blindness: 10000
    Coin: 0
    AntiKB: 50000
    Stonks: 10000
    Levitation: 50000
    Invisibility: 50000

Menus:
  ## MAIN MENU
  MainMenu:
    10:
      Material: SUNFLOWER
      DisplayName: "&eShop"
      Lore:
    11:
      Material: ENDER_PEARL
      DisplayName: "&dWarps"
      Lore:
    12:
      Material: ORANGE_DYE
      DisplayName: "&bC&ah&ea&dt"
      Lore:
    13:
      Material: PLAYER_HEAD
      DisplayName: "&7Statistics"
      Lore:
        - "&bYou own &6%coins% Coins"
    14:
      Material: POTION
      DisplayName: "&6Amplifiers"
      Lore:
    15:
      Material: DIAMOND_BOOTS
      DisplayName: "&bSuper Boots"
      Lore:
    16:
      Material: ENDER_CHEST
      DisplayName: "&5Ender Chest"
      Lore:
  ## SHOP MENU
  ShopMenu:
    12:
      Material: CHORUS_FRUIT
      DisplayName: "&5Teleportations"
      Lore:
    13:
      Material: EMERALD_ORE
      DisplayName: "&b&2Ores"
      Lore:
    14:
      Material: BOW
      DisplayName: "&cWeapons"
      Lore:
  WarpMenu:
    9:
      Material: ENDER_EYE
      DisplayName: "&7Spawn"
      Lore:
    11:
      Material: ENDER_EYE
      DisplayName: "&bVIP"
      Lore:
    13:
      Material: ENDER_EYE
      DisplayName: "&6MVP"
      Lore:
    15:
      Material: ENDER_EYE
      DisplayName: "&dULTRA"
      Lore:
    17:
      Material: ENDER_EYE
      DisplayName: "&dS&bp&ae&ec&ci&3a&6l"
      Lore:
        - "&aCost: &6500 Coins"
  OrePurchaseMenu:
    11:
      Material: EMERALD
      DisplayName: "Purchase 64"
      Lore:
        - "&aCost: &6%cost% Coins"
    13:
      Material: EMERALD
      DisplayName: "Purchase 32"
      Lore:
        - "&aCost: &6%cost% Coins"
    15:
      Material: EMERALD
      DisplayName: "Purchase 1"
      Lore:
        - "&aCost: &6%cost% Coins"
  TeleportationsMenu:
    10:
      Material: EMERALD
      DisplayName: "&aEmerald"
      Lore:
    11:
      Material: DIAMOND_BLOCK
      DisplayName: "&bDiamond Block"
      Lore:
    12:
      Material: DIAMOND
      DisplayName: "&bDiamond"
      Lore:
    14:
      Material: GOLD_INGOT
      DisplayName: "&eGold"
      Lore:
    13:
      Material: GOLD_BLOCK
      DisplayName: "&eGold Block"
      Lore:
    15:
      Material: IRON_BLOCK
      DisplayName: "&fIron Block"
      Lore:
    16:
      Material: IRON_INGOT
      DisplayName: "&fIron"
      Lore:

  WeaponsMenu:
    9:
      Material: SNOWBALL
      DisplayName: "&fKnockback"
      Lore:
        - "&bGives a little punch :)"
    11:
      Material: SLIME_BALL
      DisplayName: "&aPosition Swap"
      Lore:
        - "&bSwaps positions with whom you hit."
    13:
      Material: TNT
      DisplayName: "&cTNT"
      Lore:
        - "&bUh, it's obvious what this does. Right?"
    15:
      Material: FIRE_CHARGE
      DisplayName: "&4Fireball"
      Lore:
        - "&bYou ever wanted to become a Human Ghast? Here's your chance!"
    17:
      Material: EGG
      DisplayName: "&eInstant Kill"
      Lore:
        - "&bIt's embarrassing how overpowered this bad boy is... Enjoy!"

  ChatMenu:
    10:
      Material: LIGHT_GRAY_CONCRETE
      DisplayName: "&7Gray"
      Lore:
    11:
      Material: LIME_CONCRETE
      DisplayName: "&aLime Green"
      Lore:
    12:
      Material: YELLOW_CONCRETE
      DisplayName: "&eYellow"
      Lore:
    14:
      Material: LIGHT_BLUE_CONCRETE
      DisplayName: "&bBlue"
      Lore:
    15:
      Material: ORANGE_CONCRETE
      DisplayName: "&6Gold"
      Lore:
    16:
      Material: MAGENTA_CONCRETE
      DisplayName: "&dLight Purple"
      Lore:

  AmplifiersMenu:
    10:
      Material: LINGERING_POTION
      DisplayName: "&dMultipliers"
      Lore:
        - "&bIncreases the amount of items gained by %multiplierMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
    13:
      Material: LINGERING_POTION
      DisplayName: "&aBoosters"
      Lore:
        - "&bSpeeds up the spawn rate of items by %boosterMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
    16:
      Material: LINGERING_POTION
      DisplayName: "&6Coins Multipliers"
      Lore:
        - "&bDuh, it increases the amount of coins you can get!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
  MultipliersMenu:
    10:
      Material: POTION
      DisplayName: "&c%multLength1% &7Hour &dMultiplier"
      Lore:
        - "&bIncreases the amount of items gained by %multiplierMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
    13:
      Material: SPLASH_POTION
      DisplayName: "&c%multLength2% &7Hour &dMultiplier"
      Lore:
        - "&bIncreases the amount of items gained by %multiplierMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
    16:
      Material: LINGERING_POTION
      DisplayName: "&c%multLength3% &7Hour &dMultiplier"
      Lore:
        - "&bIncreases the amount of items gained by %multiplierMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
  BoostersMenu:
    10:
      Material: POTION
      DisplayName: "&c%boostLength1% &7Hour &dBooster"
      Lore:
        - "&bSpeeds up the spawn rate of items by %boosterMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
    13:
      Material: SPLASH_POTION
      DisplayName: "&c%boostLength2% &7Hour &dBooster"
      Lore:
        - "&bSpeeds up the spawn rate of items by %boosterMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
    16:
      Material: LINGERING_POTION
      DisplayName: "&c%boostLength3% &7Hour &dBooster"
      Lore:
        - "&bSpeeds up the spawn rate of items by %boosterMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"

  CoinsMultMenu:
    10:
      Material: POTION
      DisplayName: "&c%coinsMultLength1% &7Hour &dCoin Multiplier"
      Lore:
        - "&bIncreases the amount of coins you get per kill by %coinsMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
    13:
      Material: SPLASH_POTION
      DisplayName: "&c%coinsMultLength2% &7Hour &dCoin Multiplier"
      Lore:
        - "&bIncreases the amount of coins you get per kill by %coinsMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"
    16:
      Material: LINGERING_POTION
      DisplayName: "&c%coinsMultLength3% &7Hour &dCoin Multiplier"
      Lore:
        - "&bIncreases the amount of coins you get per kill by %coinsMult%x!"
        - "&BPurchase one at &eStore&f.&EHeightsMC&f.&Ecom"






